name: Handle issues
on: 
  workflow_dispatch:
  issues:
    types:
      - opened
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"